version: '3.8'
services:
  dev-db: 
    image: postgres
    environment:
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nesttest
    ports:
      - "5431:5432"
    networks:
      - localnetwork
networks: 
  localnetwork:
